# Generated by Django 4.2.9 on 2024-05-11 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="simGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("globalDemandP1", models.IntegerField()),
                ("globalDemandP2", models.IntegerField()),
                ("globalDemandP3", models.IntegerField()),
                (
                    "simgame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="simGame.simgame",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("priceP1", models.DecimalField(decimal_places=2, max_digits=8)),
                ("priceP2", models.DecimalField(decimal_places=2, max_digits=8)),
                ("priceP3", models.DecimalField(decimal_places=2, max_digits=8)),
                ("pubBrand", models.DecimalField(decimal_places=2, max_digits=8)),
                ("pubP1", models.DecimalField(decimal_places=2, max_digits=8)),
                ("pubP2", models.DecimalField(decimal_places=2, max_digits=8)),
                ("pubP3", models.DecimalField(decimal_places=2, max_digits=8)),
                ("payDelP1", models.IntegerField()),
                ("payDelP2", models.IntegerField()),
                ("payDelP3", models.IntegerField()),
                ("prodOrderP1", models.IntegerField()),
                ("prodOrderP2", models.IntegerField()),
                ("prodOrderP3", models.IntegerField()),
                ("acqMoul", models.IntegerField()),
                ("acqFin", models.IntegerField()),
                ("cesMoul", models.IntegerField()),
                ("cesFin", models.IntegerField()),
                ("newLeasingMoul", models.IntegerField()),
                ("newLeasingFin", models.IntegerField()),
                ("comWood1", models.DecimalField(decimal_places=2, max_digits=8)),
                ("comWood2", models.DecimalField(decimal_places=2, max_digits=8)),
                ("comWood3", models.DecimalField(decimal_places=2, max_digits=8)),
                ("comPlastic1", models.DecimalField(decimal_places=2, max_digits=8)),
                ("comPlastic2", models.DecimalField(decimal_places=2, max_digits=8)),
                ("comPlastic3", models.DecimalField(decimal_places=2, max_digits=8)),
                ("commercialRepHirings", models.IntegerField()),
                ("commercialRepDismissals", models.IntegerField()),
                (
                    "commercialRepBaseSalary",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "commercialRepCommisions",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("productionDirHirings", models.IntegerField()),
                ("productionDirDismissals", models.IntegerField()),
                (
                    "productionDirBaseSalary",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("productionExecHirings", models.IntegerField()),
                ("productionExecDismissals", models.IntegerField()),
                (
                    "productionExecBaseSalary",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("productionEmpHirings", models.IntegerField()),
                ("productionEmpDismissals", models.IntegerField()),
                (
                    "productionEmpBaseSalary",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("supplyDirHirings", models.IntegerField()),
                ("supplyDirDismissals", models.IntegerField()),
                (
                    "supplyDirBaseSalary",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("supplyExecHirings", models.IntegerField()),
                ("supplyExecDismissals", models.IntegerField()),
                (
                    "supplyExecBaseSalary",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("supplyEmpHirings", models.IntegerField()),
                ("supplyEmpDismissals", models.IntegerField()),
                (
                    "supplyEmpBaseSalary",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("administrationDirHirings", models.IntegerField()),
                ("administrationDirDismissals", models.IntegerField()),
                (
                    "administrationDirBaseSalary",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("administrationExecHirings", models.IntegerField()),
                ("administrationExecDimissals", models.IntegerField()),
                ("administrationExecBaseSalary", models.IntegerField()),
                ("administrationEmpHirings", models.IntegerField()),
                ("administrationEmpDismissals", models.IntegerField()),
                (
                    "administrationEmpBaseSalary",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "savingsInvestment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "savingsWithdrawal",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("insuranceSubscription", models.BooleanField()),
                ("scoreQAP1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scoreQAP2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scoreQAP3", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scoreQPP1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scoreQPP2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scoreQPP3", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scoreSatP1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scoreSatP2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scoreSatP3", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "scorePubBrandP1",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "scorePubBrandP2",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "scorePubBrandP3",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("scorePubP1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scorePubP2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scorePubP3", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scorePayDelP1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scorePayDelP2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scorePayDelP3", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "scoreSellingForceP1",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "scoreSellingForceP2",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "scoreSellingForceP3",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("salesP1", models.IntegerField()),
                ("salesP2", models.IntegerField()),
                ("salesP3", models.IntegerField()),
                (
                    "simgame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="simGame.simgame",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommonComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seasonalCoefM1P1",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM2P1",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM3P1",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM4P1",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM5P1",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM6P1",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM7P1",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM8P1",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM9P1",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM10P1",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM11P1",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM12P1",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM1P2",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM2P2",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM3P2",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM4P2",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM5P2",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM6P2",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM7P2",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM8P2",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM9P2",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM10P2",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM11P2",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM12P2",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM1P3",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM2P3",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM3P3",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM4P3",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM5P3",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM6P3",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM7P3",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM8P3",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM9P3",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM10P3",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM11P3",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "seasonalCoefM12P3",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("initPhaseP1", models.CharField(max_length=10)),
                ("initPhaseP2", models.CharField(max_length=10)),
                ("initPhaseP3", models.CharField(max_length=10)),
                (
                    "simgame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="simGame.simgame",
                    ),
                ),
            ],
        ),
    ]
