# Generated by Django 4.2.9 on 2024-05-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("simGame", "0002_company_owner_simgame_host_alter_company_simgame_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="simgame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="simGame.simgame"
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="simgame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="simGame.simgame"
            ),
        ),
    ]
