# Generated by Django 4.2.9 on 2024-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simGame", "0003_alter_company_simgame_alter_market_simgame"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="acqFin",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="acqMoul",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="administrationDirBaseSalary",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="administrationDirDismissals",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="administrationDirHirings",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="administrationEmpBaseSalary",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="administrationEmpDismissals",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="administrationEmpHirings",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="administrationExecBaseSalary",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="administrationExecDimissals",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="administrationExecHirings",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="cesFin",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="cesMoul",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="comPlastic1",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="comPlastic2",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="comPlastic3",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="comWood1",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="comWood2",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="comWood3",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="commercialRepBaseSalary",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="commercialRepCommisions",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="commercialRepDismissals",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="commercialRepHirings",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="insuranceSubscription",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="newLeasingFin",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="newLeasingMoul",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="payDelP1",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="payDelP2",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="payDelP3",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="priceP1",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="priceP2",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="priceP3",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="prodOrderP1",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="prodOrderP2",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="prodOrderP3",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="productionDirBaseSalary",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="productionDirDismissals",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="productionDirHirings",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="productionEmpBaseSalary",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="productionEmpDismissals",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="productionEmpHirings",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="productionExecBaseSalary",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="productionExecDismissals",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="productionExecHirings",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="pubBrand",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="pubP1",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="pubP2",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="pubP3",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="salesP1",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="salesP2",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="salesP3",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="savingsInvestment",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="savingsWithdrawal",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scorePayDelP1",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scorePayDelP2",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scorePayDelP3",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scorePubBrandP1",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scorePubBrandP2",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scorePubBrandP3",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scorePubP1",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scorePubP2",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scorePubP3",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scoreQAP1",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scoreQAP2",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scoreQAP3",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scoreQPP1",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scoreQPP2",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scoreQPP3",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scoreSatP1",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scoreSatP2",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scoreSatP3",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scoreSellingForceP1",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scoreSellingForceP2",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="scoreSellingForceP3",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="supplyDirBaseSalary",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="supplyDirDismissals",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="supplyDirHirings",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="supplyEmpBaseSalary",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="supplyEmpDismissals",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="supplyEmpHirings",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="supplyExecBaseSalary",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="supplyExecDismissals",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="supplyExecHirings",
            field=models.IntegerField(null=True),
        ),
    ]
