# Generated by Django 4.2.9 on 2024-05-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("simGame", "0005_alter_company_acqfin_alter_company_acqmoul_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simgame",
            name="scenario",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="simgame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="simGame.simgame"
            ),
        ),
    ]
