# Generated by Django 4.2.9 on 2024-05-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simGame", "0007_simgame_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="simgame",
            name="duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="simgame",
            name="maxCompanies",
            field=models.IntegerField(null=True),
        ),
    ]
