# Generated by Django 4.2.9 on 2024-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simGame", "0009_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="level",
            field=models.IntegerField(null=True),
        ),
    ]
