# Generated by Django 4.2.9 on 2024-05-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simGame", "0010_userprofile_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="decisionsSaved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="is_simulated",
            field=models.BooleanField(default=False),
        ),
    ]
