# Generated by Django 4.2.9 on 2024-06-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simGame", "0012_commoncomponent_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="revenueVariation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="salesVariations",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
