# Generated by Django 4.2.9 on 2024-06-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simGame", "0013_company_revenuevariation_company_salesvariations"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="revenueGlob",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="revenueP1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="revenueP2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="revenueP3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="salesGlob",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
