# Generated by Django 4.2.9 on 2024-06-08 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simGame", "0014_company_revenueglob_company_revenuep1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="revenueVariation",
            new_name="revenueVariations",
        ),
    ]
