# Generated by Django 4.2.9 on 2024-06-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simGame", "0015_rename_revenuevariation_company_revenuevariations"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="marketParP2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="marketPartP1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="marketPartP3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
