# Generated by Django 4.2.9 on 2024-06-08 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simGame", "0016_company_marketparp2_company_marketpartp1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="marketParP2",
            new_name="marketPartP2",
        ),
    ]
